name: Voir Tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'Support/Voir Scene/*'
      - 'backup/**'
  
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'Support/Voir Scene/*'
      - 'backup/**'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install jq
      uses: dcarbone/install-jq-action@v1.0.1
            
    - name: Test Voir
      run: |
        cd Support/VoirDemo
        DEVICES=$(xcrun simctl list -j devices available)
        SIMULATORNAME=$(echo "$DEVICES" | jq -r '.devices | to_entries[] | (.key | capture("com\\.apple\\.CoreSimulator\\.SimRuntime\\.iOS-(?<version>.+)")) as {$version} | .value[] | {name: "\(.name),OS=\($version|sub("-"; "."))"} | first(.[])' | head -n 1)
        xcodebuild test -scheme "VoirDemo" -destination "platform=iOS Simulator,name=${SIMULATORNAME}" -skip-testing:VoirTests/VoirControllerTests/testComponentWithoutOutputConformance -skip-testing:VoirTests/VoirControllerTests/testViewModelWithoutInputConformance | xcpretty
