name: Voir Tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'Support/Voir Scene/*'
      - 'backup/**'

  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'Support/Voir Scene/*'
      - 'backup/**'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install jq
      uses: dcarbone/install-jq-action@v1.0.1

    - name: Test Voir
      run: |
        DESTINATION=`swift .github/scripts/obtain-simulator.swift`
        cd Support/VoirDemo
        xcodebuild test -scheme "VoirDemo" -destination "${DESTINATION}" \
            -skip-testing:VoirTests/VoirControllerTests/testComponentWithoutOutputConformance \
            -skip-testing:VoirTests/VoirControllerTests/testViewModelWithoutInputConformance \
            | xcpretty
